name: Push Check

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21

      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Prepare Service-Comb-Center
        run: |
          make prepare
      - name: Check License Header
        uses: apache/skywalking-eyes/header@501a28d2fb4a9b962661987e50cf0219631b32ff
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: typos-action
        uses: crate-ci/typos@v1.2.1

      - name: Lint
        run: |
          go vet -stdmethods=false $(go list ./...)
          go install mvdan.cc/gofumpt@v0.2.0
          test -z "$(gofumpt -l -extra .)"
      - name: Unit Test
        run: go test -v -race -covermode=atomic -coverprofile=coverage.out ./...
        env:
          serverAddr: 127.0.0.1
          serverPort: 30100

      - name: Benchmark
        run: go test -bench=. -benchmem -run=none ./...